### PR TITLE
adding benq support

### PR DESCRIPTION
**Pull request by ZippierOstrich1**
not working yet

### CODE REVIEW

**Comment by fredrik-eriksson** [comment]
Hi, Thanks for the PR, I think it would be a bit boring to merge code that doesn't work yet. If there are any specific problem you encounter during the implementation please open an issue and we'll try to solve it. I'll leave this open so you can update it when you have something that works.

**Comment by ZippierOstrich1** [comment]
got it working

**Comment by petterreinholdtsen** [comment]
This change look good to me.

**Comment by fredrik-eriksson** [comment]
Cool! Thanks for the contribution!

**Pull request merged**
