### PR TITLE
Move cooling period from user configuration to projector specific setting.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
The setting is model specific, and should not require user intervention.

### CODE REVIEW

**Comment by fredrik-eriksson** [comment]
Yes, maybe... This is a plugin you have to configure anyway (I've changed all defaults to false since I don't want to throw out commands to whatever happens to be connected to ttyUSB0 when they install the plugin), so having a cooldown setting with an arbitrary high value (like 60 or even 90 seconds) that the user can change to whatever suits them probably isn't a great inconvenience.

That said, I'm not totally against it, but in that case it should be unique (or at least possible to override) for specific models, and not generic for the vendor. I imagine epson may have projectors that are both faster and slower than mine for cooldown. It may also depend on the environment the projector is in. It may take longer to cool in a hot environment for example. I've actually seen people put their projector in a small box with a window to make it more quiet... I don't think the projector lamp likes that though.

**Comment by petterreinholdtsen** [comment]
[Fredrik Eriksson]
> Yes, maybe... This is a plugin you have to configure anyway (I've
> changed all defaults to false since I don't want to throw out commands
> to whatever happens to be connected to ttyUSB0 when they install the
> plugin),

The current code will not throw out commands to whatever happens to be
connected, it will verify the proper reponse using _verify_connection()
before doing anything more.

> so having a cooldown setting with an arbitrary high value (like 60 or
> even 90 seconds) that the user can change to whatever suits them
> probably isn't a great inconvenience.

Note, the 60 second value for InFocus is specified in the documentation.
It is impossible to turn on the projector again before this time period
is over. This is not really related to the lamp temperature.

> That said, I'm not totally against it, but in that case it should be
> unique (or at least possible to override) for specific models, and not
> generic for the vendor. I imagine epson may have projectors that are
> both faster and slower than mine for cooldown. It may also depend on
> the environment the projector is in. It may take longer to cool in a
> hot environment for example. I've actually seen people put their
> projector in a small box with a window to make it more quiet... I
> don't think the projector lamp likes that though.

The point of this feature in the ad-on is to make sure the 'turn on'
instructions actually take effect, not to protect the lamp.  Lamp
protection is the domain of the projector producer.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by fredrik-eriksson** [comment]
Well, the _verify_connection() is not meant to verify that the projector on the other end is correct. It's never called from anywhere outside of the ProjectorInstance class (I use '\_' as a prefix for variables and functions that should not be used outside of their file or class). The purpose of _verify_connection() in the epson class is to verify that the projector is ready to communicate, as the protocol specifies that the projector is ready when it returns a ':' in response for a carriage return. It's just a sanity check. 

Enabling the plugin with the "activate projector on kodi start" option will send out at least '\r' to the serial device. But there is no standard for serial protocols, meaning the device in the other end (if it's not the correct projector) could mess up because of this single CR. In best case nothing happens, but it could be programmed to shutdown at CR, alter voltage, switch a relay or just about anything else... Serial interface is common on hobby electronic projects, and when designing the protocol for those you usually get lazy and make it as simple as possible with very little error-checking, since you're the only one who will use it anyway. So while the chances are slim that whatever we send will cause any sort of trouble it's still better to play it safe and let the user tell you where and what model the projector is. (This is also why I'm not a fan of the idea of auto-detecting projector model - the error handling on serial interfaces tend to be really sloppy).

Your model may use time to decide for how long it will cool, but others may use temperature sensors, and those may not need the same cooldown period depending on the environment they are in. In that case any setting we hardcode for a projector model need to be long enough for worst case scenario. It might not differ much, but it's hard to know. I think it's better to have a long default (say 90 seconds) and then the user can adopt it to whatever works for them if they think it's too long.

**Comment by fredrik-eriksson** [comment]
I'm archiving this project as I have no need for it anymore and generally was not very active on it anyway. Feel free to continue development in your fork if you still find it useful.

**Pull request closed without merging**
