### PR TITLE
acer

### PR DESCRIPTION
**Pull request by datendelphin**
Today I experimented a bit with my acer beamer. It works partially. Turning on and off works.

The beamer seems to need a lot of time to process commands, to be ready for the next. I hacked an ugly sleep into the code. I also disabled the verify command with a hard return True, because I did not find a way to verify without running a command that incurs another sleep.
I'm not sure why select.select is used. a simple serial.read() would be sufficient it seems, and would automatically sleep for timeout amount.

Setting the input source when waking up does not work. There, it seems the beamer would need a lot more time before it can accept the source selection. Not sure how that should be solved. Setting the input when it is turned on (starting kodi) works

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Are you lacking documentation on the protocol, or is there some other reason why you are not sure how this work?

**Comment by datendelphin** [comment]
The dirty solution would be: sleep for 10 seconds after starting the beamer. I don't know how plugins work in cody, if that wait would be asynchronous. Second, I would check first which source is selected, select the correct one if needed, and repeat that a few times (if still the wrong source is selected) to give the beamer enough time to properly start up. But that would be a major change in the framework of this plugin. So I would like some feedback from the maintainer how this issue is tackled best, as it requires more than just adding a few new rs232 commands for a new beamer type.

**Comment by fredrik-eriksson** [comment]
You have very much freedom to do stuff in your vendor-specific library. The only requirements is that it contains the class ProjectorInstance and all methods from epson.py that does not start with a '_'. As for *how* the methods are implemented; that's up to each library as each vendor has it's own protocol and quirks. You're free to use serial.read() instead of select if you think that's better. Throw in some sleep if needed, or create an advanced queueing system for asynchronous commands if the projector requires it.

When powering the projector on the ProjectorInstance.send_command() method will be called with lib.CMD_PWR_ON as argument and the source selection (if configured) will not be run until the function returns. If you have a way to detect when the projector is ready to accept commands again you can do that here (or just as you suggested: sleep) before returning. 

I don't think sleeping for 10 seconds after power on would be particularly dirty. The add-on runs asynchronous, but even if it were not... I don't know about your projector, but mine takes more than 10 seconds from start-command to warmed-up and properly displaying a picture anyway. :shrug: 

Since you're the contributor for this acer library: Implement it in any way that makes it useful for you.

**Comment by petterreinholdtsen** [comment]
This code no longer merge without conflicts.  Perhaps you got time to update it and make it ready for general consumtion?

**Comment by datendelphin** [comment]
Yes, I will try to rebase it. Might also tinker a bit with switching to the right source after start up.
One question about that @fredrik-eriksson : CMD_SRC_QUERY is never used? Selecting a source, even if it is the same, blanks the picture for a few seconds on my beamer. To avoid delay, I would best check first if the correct source was already selected inside the library. Because the source selection is unconditionally triggered.

**Comment by fredrik-eriksson** [comment]
CMD_SRC_QUERY is used by the REST-API for querying the current power and source status of the projector, but I don't think anything in the kodi controls uses it. You could intercept the CMD_SRC_SET command in the send_command()-method and do your check there. Something like this (pseudo code):
```
if command == lib.CMD_SRC_SET:
  current_src = <ask_projector_for_current_source>
  if current_src != kwargs['source_id']:
    <ask_projector_to_change_source>
else:
  return
```

But I guess it could also be done in the calling function (commands.set_source()) to be consistent for all vendors. I would merge a separate PR for that, or I might implement it myself eventually...

**Comment by datendelphin** [comment]
I just pushed another variant, this one now should be fit for merge.
The acer.py has now generous sleep() commands to wait for the projector to settle after critical commands (power on, switch source). It also checks on its own if those two commands are necessary. Works at least for me. Thanks for the explanations.

**Comment by fredrik-eriksson** [comment]
Nice, thanks for your contribution!

**Pull request merged**
